#!/usr/bin/env bash

# This script is a convenience wrapper for dotdrop. It can be executed from
# any dorectory, and will run the dotdrop command for user/root, or for both.
#
# Arguments:
#   - $1: the user dotdrop will be executed for. Can be one of 'user', 'root'
#         or 'both'.
#   - $2: the dotdrop command that will be executed.
#   - $3+: options and arguments for dotdrop.
#
# Environment:
#   - $DOTFILES_HOME: the directory where Pipfile and dotdrop.sh are located.
#                     Defaults to $HOME/Files/Programming/sys/dotfiles.

#######################################
# Variables
#######################################

DOTFILES_HOME="${DOTFILES_HOME:-$HOME/Files/Programming/sys/dotfiles}"

#######################################
# Input processing
#######################################

WHO="$1"
CMD="$2"
shift 2

WRONG_USER=''
case "$WHO" in
    user|root|both)
        ;;
    '')
        WRONG_USER='no user'
        ;;
    *)
        WRONG_USER="'$WHO' user"
        ;;
esac
[ -n "$WRONG_USER" ] && {
    echo >&2 "Error: $WRONG_USER given. Muse be one of 'user', 'root' or" \
        "'both'"
    exit 1
}

# Relative paths need to be resolved before cd-ing, otherwise they won't work
ARGS=()
for ARG in "$@"; do
    [ -e "$ARG" ] && ARG="$(readlink -f "$ARG")"
    ARGS+=("$ARG")
done

#######################################
# Executing dotdrop
#######################################

# Will exit the exript if $DOTFILES_HOME is not defined and
# $HOME/Files/Programming/sys/dotfiles doesn't exist
cd $DOTFILES_HOME || exit

case "$WHO" in
    user|both)
        pipenv run bash dotdrop.sh "$CMD" -c 'config-user.yaml' "${ARGS[@]}"
        ;;
esac

case "$WHO" in
    root|both)
        sudo -E pipenv run bash dotdrop.sh "$CMD" -c 'config-root.yaml' \
            "${ARGS[@]}"
        ;;
esac

cd - &> /dev/null || exit
