#!/bin/sh

# This script logs to syslog based on the status passed as the first arguent:
# if it's not an error, it logs a prefedined message with the given priority,
# defaulting to info; if it's an error, it logs the status itself with error
# priority.
#
# Arguments:
#   - $1: Status code to be logged.
#   - $2: Tag t be used with syslog.
#   - $3: Syslog facility to be used (default: local0).
#   - $4: Syslog priority to be used for non-error statuses (default: info).

#######################################
# Input ptocessing
#######################################

STATUS="$1"
TAG="$2"
FACILITY="${3:-local0}"
LEVEL="${4:-info}"

#######################################
# Variables
#######################################

MSG='OK'
[ "$STATUS" -ne 0 ] && {
    LEVEL='error'
    MSG="Error $STATUS"
}

#######################################
# Logging
#######################################

logger -p "$FACILITY.$LEVEL" -t "$TAG" "$MSG"
